name: Periodic Health Check

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55,60 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed app url
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fsopokedexaas.herokuapp.com
          max-attempts: 3
          retry-delay: 5s
