name: Periodic Health Check

on:
  push:
    branch:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronized]

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed app url
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://fsopokedexaas.herokuapp.com
          max-attempts: 3
          retry-delay: 5s
