name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: logging github.event
        env: 
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "${{ GITHUB_EVENT }}"
      - name: trying to fail
        run: exit 1          
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: heroku deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fsopokedexaas"
          heroku_email: "aliadadehmav@gmail.com"
          healthcheck: "https://fsopokedexaas.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
      - name: build failed notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with: 
          severity: error
          description: commit \n ${{ github.event.payload.head_commit.url }} by As broke the build.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: build success notification
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          description: to https://fsopokedexaas.herokuapp.com by As
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        
          
  tag_release:
    needs: [simple_deployment_pipeline]
    if: 
      ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
